title: SpecFlow
url: "https://deeptts.github.io/specflow/"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/deeptts/specflow"
footer_text: "A Linear Spectrogram Generative Model for Speech Synthesis"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
